"""add image_url field to Media

Revision ID: 3a9c9c7c3e69
Revises: cc53dc4b7b94
Create Date: 2025-04-02 14:54:17.674842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a9c9c7c3e69'
down_revision: Union[str, None] = 'cc53dc4b7b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'image_url')
   
    # ### end Alembic commands ###
