"""set null to models

Revision ID: cc53dc4b7b94
Revises: dbea14bc755f
Create Date: 2025-03-28 15:03:50.573896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc53dc4b7b94'
down_revision: Union[str, None] = 'dbea14bc755f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_parent_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['category_id'], ondelete='SET NULL')
    op.drop_constraint('user_wishlist_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'wishlist', ['wishlist_id'], ['wishlist_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_wishlist_id_fkey', 'user', 'wishlist', ['wishlist_id'], ['wishlist_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_parent_id_fkey', 'category', 'category', ['parent_id'], ['category_id'])
   
