"""Create ecommerce tables

Revision ID: dbea14bc755f
Revises: 
Create Date: 2025-03-26 22:22:32.037509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbea14bc755f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['parent_id'], ['category.category_id'], ),
                    sa.PrimaryKeyConstraint('category_id')
                    )
    op.create_table('propertyname',
                    sa.Column('property_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('property_id')
                    )
    op.create_table('wishlist',
                    sa.Column('wishlist_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('wishlist_id')
                    )
    op.create_table('product',
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=512), nullable=False),
                    sa.Column('description', sa.String(
                        length=1024), nullable=True),
                    sa.Column('price', sa.DECIMAL(), nullable=False),
                    sa.Column('available', sa.Boolean(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['category.category_id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('product_id')
                    )
    op.create_table('property',
                    sa.Column('description_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(
                        length=256), nullable=False),
                    sa.Column('property_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['property_id'], ['propertyname.property_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('description_id')
                    )
    op.create_table('user',
                    sa.Column('user_id', sa.BIGINT(),
                              autoincrement=False, nullable=False),
                    sa.Column('username', sa.String(
                        length=128), nullable=True),
                    sa.Column('full_name', sa.String(
                        length=128), nullable=False),
                    sa.Column('email', sa.String(length=128), nullable=True),
                    sa.Column('phone', sa.String(length=32), nullable=True),
                    sa.Column('active', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('wishlist_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['wishlist_id'], ['wishlist.wishlist_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('media',
                    sa.Column('media_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('telegram_media_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('media_type', sa.Enum('photo', 'video',
                                                    name='mediatype'), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('alt_text', sa.String(
                        length=128), nullable=True),
                    sa.Column('is_feature', sa.Boolean(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['product.product_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('media_id'),
                    sa.UniqueConstraint('telegram_media_id')
                    )
    op.create_table('productproperties',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('property_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['product.product_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['property_id'], ['property.description_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('referal',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('referrers_id', sa.BIGINT(), nullable=False),
                    sa.Column('refers_id', sa.BIGINT(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['referrers_id'], ['user.user_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['refers_id'], ['user.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('wishlistproducts',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('wishlist_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['product.product_id'], ),
                    sa.ForeignKeyConstraint(
                        ['wishlist_id'], ['wishlist.wishlist_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlistproducts')
    op.drop_table('referal')
    op.drop_table('productproperties')
    op.drop_table('media')
    op.drop_table('user')
    op.drop_table('property')
    op.drop_table('product')
    op.drop_table('wishlist')
    op.drop_table('propertyname')
    op.drop_table('category')
    # ### end Alembic commands ###
